# Generated by Django 3.1.5 on 2021-01-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quote',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
